fixes `callWasMoved` with inheritable objects (#1249)
ref
https://github.com/nim-lang/nimony/issues/1246#issuecomment-3024316862

```nim
nimcache/tesp9owq11.c:448:68: error: no member named 'ri_0_tesp9owq11' in 'struct ArefSX4eodeX4fbj0tesp9owq11_0_t'
  448 |     eQwasmovedQ_ArefSX4eodeX4fbj0tesp9owq11_0_tesp9owq11((&(*jt_0).ri_0_tesp9owq11));}
      |                                                            ~~~~~~~ ^
1 error generated.
```

We need to transform the parameter of `=wasmoved` to fix field levels